#!/usr/bin/env python3
"""Generate the 16-pixel-high 1bpp ASCII font embedded by the demo UI."""

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True, help="Path to a TTF font")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    font = ImageFont.truetype(args.font, 16)
    rows = []
    widths = []
    for codepoint in range(0x20, 0x7F):
        width = round(font.getlength(chr(codepoint)))
        if width <= 0 or width > 16:
            raise ValueError(
                f"U+{codepoint:04X} has unsupported advance width {width}"
            )

        image = Image.new("1", (16, 16), 0)
        draw = ImageDraw.Draw(image)
        draw.text((0, -2), chr(codepoint), font=font, fill=1)
        glyph = []
        for y in range(16):
            value = 0
            for x in range(16):
                value = (value << 1) | int(image.getpixel((x, y)) != 0)
            glyph.append(value)
        rows.append((codepoint, glyph))
        widths.append(width)

    output = [
        "// Generated by tools/generate_ascii_font.py from TRMNL16 Regular.",
        "// ASCII U+0020..U+007E, proportional width, 16 pixels high.",
        "#ifndef ZECTRIX_ASCII_FONT_8X16_H_",
        "#define ZECTRIX_ASCII_FONT_8X16_H_",
        "",
        "#include <cstdint>",
        "",
        "inline constexpr uint16_t kZectrixAsciiFont8x16[95][16] = {",
    ]
    for codepoint, glyph in rows:
        values = ", ".join(f"0x{value:04x}" for value in glyph)
        output.append(f"    {{{values}}},  // 0x{codepoint:02X}")
    output.extend(
        [
            "};",
            "",
            "inline constexpr uint8_t kZectrixAsciiFontWidths[95] = {",
        ]
    )
    for start in range(0, len(widths), 16):
        values = ", ".join(str(width) for width in widths[start : start + 16])
        output.append(f"    {values},")
    output.extend(["};", "", "#endif  // ZECTRIX_ASCII_FONT_8X16_H_", ""])
    Path(args.output).write_text("\n".join(output), encoding="utf-8")


if __name__ == "__main__":
    main()
