#ifndef ZECTRIX_BOARD_CONFIG_H_
#define ZECTRIX_BOARD_CONFIG_H_

#include "driver/gpio.h"

#define ZECTRIX_AUDIO_SAMPLE_RATE 16000
#define ZECTRIX_AUDIO_MCLK GPIO_NUM_14
#define ZECTRIX_AUDIO_WS GPIO_NUM_38
#define ZECTRIX_AUDIO_BCLK GPIO_NUM_15
#define ZECTRIX_AUDIO_DIN GPIO_NUM_16
#define ZECTRIX_AUDIO_DOUT GPIO_NUM_45
#define ZECTRIX_AUDIO_PA GPIO_NUM_46
#define ZECTRIX_I2C_SDA GPIO_NUM_47
#define ZECTRIX_I2C_SCL GPIO_NUM_48
#define ZECTRIX_AUDIO_POWER GPIO_NUM_42

#define ZECTRIX_BUTTON_OK GPIO_NUM_0
#define ZECTRIX_BUTTON_UP GPIO_NUM_39
#define ZECTRIX_BUTTON_DOWN GPIO_NUM_18

#define CHARGE_DETECT_GPIO GPIO_NUM_2
#define CHARGE_FULL_GPIO GPIO_NUM_1
#define CHARGE_DETECT_CHARGING_LEVEL 0

#define ZECTRIX_POWER_LED GPIO_NUM_3
#define ZECTRIX_RTC_INT GPIO_NUM_5
#define ZECTRIX_RTC_ADDR 0x51
#define ZECTRIX_NFC_ADDR 0x55
#define ZECTRIX_NFC_FD GPIO_NUM_7
#define ZECTRIX_NFC_POWER GPIO_NUM_21
#define ZECTRIX_NFC_FD_ACTIVE_LEVEL 0
#define ZECTRIX_VBAT_LATCH GPIO_NUM_17

#endif  // ZECTRIX_BOARD_CONFIG_H_
