[platformio]
default_envs = waveshare_epaper_esp32

[env:waveshare_epaper_esp32]
platform = espressif32@^6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -DCORE_DEBUG_LEVEL=3
lib_deps =
  zinggjm/GxEPD2@^1.6.4
  tzapu/WiFiManager@^2.0.17
  bblanchon/ArduinoJson@^7.2.1

